version: '3'
services:
  api:
    image: todo-express-app
    build: .
    networks:
      - backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://kabangabill@5432/todosdev

  web-cli:
    image: todo-express-app
    networks:
      - backend
    command: sh

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kabangabill
      POSTGRES_PASSWORD: null
      POSTGRES_DB: todosdev

networks:
  backend:
    driver: bridge